### ISSUE TITLE
Surplus pages / templates?

### ISSUE THREAD

**Issue by dmlogic** [aizlewood/PIE-patternlab#1]
There's a fair bit here that appears generic or even related to other projects. Can I assume if it doesn't obviously relate to the walkthroughs I can ignore it?

**Comment by aizlewood** [comment]
Hi Darren, correct, not all pages or templates have been finalised/culled yet.

**Comment by aizlewood** [comment]
Should mention that that refers to the homepage, which is currently being designed.
