### ISSUE TITLE
Job listing search form mis-aligned

### ISSUE THREAD

**Issue by dmlogic** [aizlewood/PIE-patternlab#2]
In Firefox dev edition the grid has gone a bit wrong, see screengrab
![screen shot 2015-11-19 at 14 27 49](https://cloud.githubusercontent.com/assets/1250252/11273193/d4f78082-8ec9-11e5-9e55-75004ffc6cd7.png)

**Comment by aizlewood** [comment]
This has been fixed using display: table-cell for the fieldset
