### ISSUE TITLE
Job application modal

### ISSUE THREAD

**Issue by dmlogic** [aizlewood/PIE-patternlab#3]
Please can you clarify which one of these I should go for? I can see one in `templates-job-description-modal-test` and `templates-job-description`. They're subtly different and each has issues in FF - either unusual scroll behaviour or odd close button (see attached) or both.
![screen shot 2015-11-19 at 14 33 11](https://cloud.githubusercontent.com/assets/1250252/11273308/7ad76f62-8eca-11e5-8276-036a3cfce445.png)

**Comment by aizlewood** [comment]
There were two types of modal being tested. Have removed old one.
