### ISSUE TITLE
Bump modal

### ISSUE THREAD

**Issue by dmlogic** [aizlewood/PIE-patternlab#9]
The walkthrough has a [bump modal](https://marvelapp.com/c2g65i#7148921), do we still want it? Functionally it's not necessary, the cart item can be added directly from the listing. If it is needed please can I have some markup.

**Comment by aizlewood** [comment]
Hi Darren, 

It might still be needed to provide additional sales/marketing copy as to what it is and what merits it has.  From what I can see in the prototype, there doesn't seem to be any area this can displayed, except via a modal.

Cheers,
Jon
